# This is a basic workflow to help you get started with Actions

name: sandbox

on:
  workflow_dispatch:
  
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world! I have a secret, ${{ secrets.SO_SECRET }}
